CLASS zcl_fabap_jul2025_exer05_rpb DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.

    CLASS-METHODS get_data
        FOR TABLE FUNCTION zi_fabap_exer04_rpb .

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_FABAP_JUL2025_EXER05_RPB IMPLEMENTATION.


  METHOD get_data BY DATABASE FUNCTION
   FOR HDB LANGUAGE SQLSCRIPT
   USING /dmo/booking.

    RETURN select * from "/DMO/BOOKING";

  ENDMETHOD.
ENDCLASS.
